This is makeindex, version 2.15 [MiKTeX 2.9] (kpathsea + Thai support).
Scanning style file C:/Users/1.5V/Documents/GitHub/LaTeX_MA_Active_Dolly/ExampleMasters.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file ExampleMasters.acn....done (438 entries accepted, 0 rejected).
Sorting entries......done (4281 comparisons).
Generating output file ExampleMasters.acr....done (172 lines written, 0 warnings).
Output written in ExampleMasters.acr.
Transcript written in ExampleMasters.alg.
