This is makeindex, version 2.15 [MiKTeX 2.9 64-bit] (kpathsea + Thai support).
Scanning style file C:/Users/Sebastian/Documents/GitHub/LaTeX_MA_Active_Dolly/ExampleMasters.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file ExampleMasters.acn....done (547 entries accepted, 0 rejected).
Sorting entries.......done (5632 comparisons).
Generating output file ExampleMasters.acr....done (209 lines written, 0 warnings).
Output written in ExampleMasters.acr.
Transcript written in ExampleMasters.alg.
